/**
 * 11 profili tłumaczeniowych (doc/02) — rdzeń produktu.
 *
 * Każdy profil steruje promptem: ton, kreatywność, ścisłość, co chronić,
 * czego unikać oraz instrukcja systemowa wstrzykiwana do modelu.
 * `creativity` mapuje się później na temperaturę, `strictness` na siłę zakazów.
 *
 * Wszystkie wartości tekstowe zapisano w literałach szablonowych (backtick),
 * aby bezpiecznie zawierały cudzysłowy z przykładów.
 */

import type { ProfileGroup, ProfileId, TranslationProfile } from "./types";

export const PROFILES: TranslationProfile[] = [
  {
    id: `product_long`,
    displayName: `Opis produktu — długi`,
    badge: `PRODUCT_LONG`,
    group: `Produktowe`,
    hint: `Karty produktowe, opisy producentów`,
    useCases: [
      `Opisy producentów`,
      `Długie opisy produktowe na karcie produktu`,
      `Sekcje "o produkcie", "dlaczego ten produkt"`,
    ],
    goal: `Naturalny, sprzedażowy opis produktu po lokalizacji, który nie zmienia ani jednego parametru technicznego i nie zmyśla cech.`,
    tone: `professional`,
    creativity: 3,
    strictness: 4,
    lengthGuidance: `Długość outputu zbliżona do źródła (±20%).`,
    optimizeFor: `Naturalny styl sprzedażowy bez zmiany faktów`,
    protect: [
      `Liczby, jednostki, kalibry, wymiary, wagi, pojemności`,
      `Nazwy marek, modeli, kolekcji, SKU`,
      `Certyfikaty i normy (EN, NIJ, MIL-STD), klasy IP / IK`,
      `Nazwy własne (MOLLE, PALS, Picatinny)`,
    ],
    avoid: [
      `Dodawania cech, których nie ma w tekście źródłowym`,
      `Dosłownego tłumaczenia idiomów`,
      `Kalk z polskiego (np. "high quality" zamiast "premium")`,
      `Przesadnej grandilokwencji, jeśli źródło jej nie ma`,
    ],
    qualityChecks: [
      `Wszystkie liczby i jednostki obecne 1:1`,
      `Brak nazw modeli, których nie ma w źródle`,
      `Długość outputu w granicach ±20% źródła`,
      `Ton dopasowany do rynku docelowego`,
    ],
    systemInstruction: `You are translating a long product description for an e-commerce store specialized in military, outdoor, tactical and survival goods. Preserve every number, unit, caliber, brand and model name exactly as in the source. Do not invent product features. Keep a professional, knowledgeable tone — like a specialized retailer, not a marketing agency. Length should be similar to the source (within +/-20%). If the source uses passive promotional language, translate it idiomatically for the target market, not literally.`,
    customInstructionsRequired: false,
    alwaysSuggestHumanReview: false,
  },
  {
    id: `product_short`,
    displayName: `Opis produktu — krótki`,
    badge: `PRODUCT_SHORT`,
    group: `Produktowe`,
    hint: `Listy, porównywarki, tabele rozmiarów`,
    useCases: [
      `Tabele rozmiarowe`,
      `Porównywarki`,
      `Instrukcje obsługi`,
      `Listy parametrów i specyfikacje techniczne`,
    ],
    goal: `Maksymalna precyzja i zwięzłość — zero stylistycznej kreatywności, zachowana struktura (wiersze, kolumny, listy).`,
    tone: `concise`,
    creativity: 1,
    strictness: 5,
    lengthGuidance: `Krótko, bez retoryki — bez rozbudowywania względem źródła.`,
    optimizeFor: `Precyzja i zachowanie struktury`,
    protect: [
      `Strukturę (markdown, tabele, listy)`,
      `Kolejność elementów`,
      `Liczby, jednostki i symbole (x, +/-, °C, mm, g, kg, ml, fps, J, MOA)`,
      `Nazwy parametrów technicznych w formie standardu rynkowego`,
    ],
    avoid: [
      `Zmiany formatu (np. zamiany tabeli na prozę)`,
      `Dodawania komentarzy i objaśnień`,
      `Konwersji jednostek (zostają w SI)`,
      `Emocjonalnego języka`,
    ],
    qualityChecks: [
      `Identyczna liczba wierszy i kolumn`,
      `Identyczne wartości liczbowe i jednostki`,
      `Identyczna kolejność elementów`,
      `Output krótki, bez retoryki`,
    ],
    systemInstruction: `You are translating short technical product content — size charts, parameter tables, instructions. Preserve the exact structure (rows, columns, lists, markdown). Preserve every number, unit and symbol literally. Do NOT convert units. Do NOT add commentary. Keep wording terse and standard for the target market. If a row is unclear, translate it as-is rather than guessing its meaning.`,
    customInstructionsRequired: false,
    alwaysSuggestHumanReview: false,
  },
  {
    id: `seo`,
    displayName: `SEO — kategorie i meta`,
    badge: `SEO`,
    group: `SEO`,
    hint: `Nazwy i opisy kategorii, meta description`,
    useCases: [
      `Nazwy kategorii`,
      `Opisy kategorii`,
      `Meta description`,
      `Nagłówki H1, breadcrumbs`,
    ],
    goal: `Lokalizacja pod intencję wyszukiwania rynku docelowego — nie tłumaczenie 1:1 polskiej frazy.`,
    tone: `professional`,
    creativity: 3,
    strictness: 3,
    lengthGuidance: `Nazwa kategorii do 60 znaków, meta description do 160 znaków.`,
    optimizeFor: `Dopasowanie do intencji wyszukiwania rynku`,
    protect: [
      `Zakres semantyczny kategorii (nie zawężamy ani nie poszerzamy)`,
      `Nazwy własne marek w kategoriach markowych`,
      `Jednostki będące częścią kategorii (np. "> 1000 lumenów")`,
    ],
    avoid: [
      `Dosłownych kalk polskiej frazy`,
      `Keyword stuffingu`,
      `Frazy 1:1 z polskiego, gdy nie jest naturalna w wyszukiwarce rynku`,
      `Zaimków "my", "nasz" w opisach kategorii`,
    ],
    qualityChecks: [
      `Nazwa kategorii do 60 znaków`,
      `Meta description do 160 znaków`,
      `Brak 3+ powtórzeń tej samej frazy`,
      `Zakres kategorii pokrywa się ze źródłem`,
    ],
    systemInstruction: `You are localizing e-commerce SEO content. Match the target market's actual search intent and wording — not a word-for-word translation of the Polish source. Preserve the semantic scope of the category exactly: do not narrow or broaden it. Avoid keyword stuffing. Keep category names short and natural for the target market. If the Polish source uses a phrase with no natural equivalent, prefer the most common phrasing real shoppers in the target country would type.`,
    customInstructionsRequired: false,
    alwaysSuggestHumanReview: false,
  },
  {
    id: `guide`,
    displayName: `Poradnik / artykuł`,
    badge: `GUIDE`,
    group: `Treści`,
    hint: `Blog, how-to, treści eksperckie`,
    useCases: [
      `Artykuły poradnikowe na blogu`,
      `Treści typu "jak wybrać", "przewodnik po"`,
      `Zestawienia "top 5"`,
    ],
    goal: `Tekst pomocny, jasny i ekspercki dla użytkownika końcowego — nie reklamowy.`,
    tone: `expert`,
    creativity: 3,
    strictness: 3,
    lengthGuidance: `Długość zbliżona do źródła, zachowana liczba sekcji.`,
    optimizeFor: `Czytelność i ekspercki, edukacyjny ton`,
    protect: [
      `Strukturę sekcji i nagłówków`,
      `Rekomendacje i wnioski autora`,
      `Nazwy modeli i marek wymienione w artykule`,
      `Wszystkie liczby (np. "2000 mAh", "kaliber 9 mm")`,
    ],
    avoid: [
      `Upraszczania merytoryki`,
      `Dorzucania własnych rekomendacji`,
      `Poprawiania autora`,
      `Tonu sprzedażowego — to nie reklama`,
    ],
    qualityChecks: [
      `Nagłówki przetłumaczone, hierarchia zachowana`,
      `Liczba sekcji równa liczbie sekcji w źródle`,
      `Nazwy modeli niezmienione`,
      `Styl redakcyjny, nie katalogowy`,
    ],
    systemInstruction: `You are translating an educational long-form article for end customers. Preserve the section structure and the author's recommendations exactly. Keep an expert, neutral-warm tone — informative, not salesy. Preserve all model names, brand names and numerical values. Do not add your own advice. If the source uses a colloquial Polish expression, translate it idiomatically for the target market.`,
    customInstructionsRequired: false,
    alwaysSuggestHumanReview: false,
  },
  {
    id: `infographic`,
    displayName: `Infografika`,
    badge: `INFOGRAPHIC`,
    group: `Treści`,
    hint: `Krótkie teksty na grafiki`,
    useCases: [
      `Napisy na grafikach`,
      `Krótkie hasła`,
      `Listy 3–5 punktów`,
      `Headline + bullet`,
    ],
    goal: `Krótko, rytmicznie i czytelnie na obrazku — z zachowaniem sensu każdej linii.`,
    tone: `professional`,
    creativity: 3,
    strictness: 3,
    lengthGuidance: `Każda linia krótka (nagłówek do ok. 40 znaków); liczba punktów równa źródłu.`,
    optimizeFor: `Krótkość, rytm i czytelność w layoucie`,
    protect: [
      `Liczbę punktów / linii (źródło ma 5, output ma 5)`,
      `Sens każdej linii`,
      `Liczby i jednostki`,
    ],
    avoid: [
      `Zdań wielokrotnie złożonych`,
      `Słów dłuższych niż 14 znaków, gdy da się krócej (layout DE/FI)`,
      `Przecinków w środku haseł`,
    ],
    qualityChecks: [
      `Długość nagłówka do ok. 40 znaków`,
      `Liczba punktów równa liczbie w źródle`,
      `Rytm utrzymany (równa długość bulletów)`,
      `Brak kropek na końcu krótkich haseł`,
    ],
    systemInstruction: `You are translating text intended for an infographic. Keep each line short, rhythmic and visually balanced. Preserve the exact number of bullet points and their order. Avoid long words where a shorter synonym exists (important for German and Finnish layout). Drop trailing periods on short headlines. Preserve all numbers and units.`,
    customInstructionsRequired: false,
    alwaysSuggestHumanReview: false,
  },
  {
    id: `marketing`,
    displayName: `Marketing`,
    badge: `MARKETING`,
    group: `Marketing`,
    hint: `Newslettery, ADS, SMS, push`,
    useCases: [
      `Newslettery`,
      `Kampanie ADS`,
      `SMS i mailingi`,
      `Push, hasła kampanijne`,
    ],
    goal: `Transkreacja — odtworzenie efektu perswazyjnego w języku docelowym, nie wierność tekstowi.`,
    tone: `persuasive`,
    creativity: 5,
    strictness: 2,
    lengthGuidance: `Długość zgodna z kanałem: SMS do 160 znaków, ADS ok. 90 znaków, newsletter ciepły i skanowalny.`,
    optimizeFor: `Perswazja i naturalne CTA na rynku docelowym`,
    protect: [
      `Intencję CTA (forma językowa dowolna)`,
      `Rabat, kwotę, kod promocyjny (% i liczby 1:1)`,
      `Daty i deadline'y`,
      `Kod kuponu (np. "SALE25")`,
    ],
    avoid: [
      `Dosłownej kalki polskiej składni`,
      `Tłumaczenia rymu lub gry słownej 1:1`,
      `Przekraczania limitu długości kanału (np. SMS)`,
      `Obietnic, których nie ma w źródle`,
    ],
    qualityChecks: [
      `Obecne wezwanie do akcji (CTA)`,
      `Rabat i kod kuponu 1:1`,
      `Długość zgodna z kanałem`,
      `Styl dopasowany do rynku docelowego`,
    ],
    systemInstruction: `You are doing transcreation, not translation. Recreate the persuasive intent of the source in the target market's natural marketing language. You may change phrasing, idioms, structure and even the metaphor — but you must preserve any discount value, dates, promo codes, and the call to action. Match the channel: SMS = max 160 characters, newsletter = warm and scannable, ADS = punchy. Avoid translating Polish wordplay literally.`,
    customInstructionsRequired: false,
    alwaysSuggestHumanReview: false,
  },
  {
    id: `ui_system`,
    displayName: `UI / System`,
    badge: `UI_SYSTEM`,
    group: `UI / System`,
    hint: `Przyciski, mikrocopy, komunikaty`,
    useCases: [
      `Przyciski w checkout`,
      `Etykiety formularzy`,
      `Komunikaty błędów`,
      `Banery, tooltipy, statusy zamówień`,
    ],
    goal: `Krótkie, jednoznaczne mikrocopy — naturalne dla rynku, nigdy dosłowne.`,
    tone: `concise`,
    creativity: 2,
    strictness: 4,
    lengthGuidance: `Przyciski do 3 słów; komunikaty krótkie i konkretne.`,
    optimizeFor: `Mikrocopy naturalne dla rynku docelowego`,
    protect: [
      `Placeholdery {variable}, %s, {{name}} — nigdy nie tłumaczyć`,
      `Znaczniki HTML i Markdown`,
      `Kolejność akcji w komunikatach (kliknij X, potem Y)`,
      `Jednostki czasu i waluty`,
    ],
    avoid: [
      `Zbyt długich komunikatów (przycisk nie staje się zdaniem)`,
      `Zaimków grzecznościowych, gdy rynek nie używa ich w UI`,
      `Kalek (np. "Add to basket" w EN-US zamiast "Add to cart")`,
      `Kreatywności — przycisk to przycisk`,
    ],
    qualityChecks: [
      `Placeholdery obecne 1:1`,
      `Przyciski do 3 słów`,
      `Zgodność z konwencją rynku (cart / basket / Warenkorb)`,
      `Brak interpunkcji końcowej w etykietach przycisków`,
    ],
    systemInstruction: `You are translating UI microcopy for an e-commerce store. Use the wording your target market actually uses in real online stores — not a literal Polish translation. Keep placeholders ({variable}, %s, {{name}}) intact. Keep buttons very short (max 3 words). Preserve any HTML or Markdown tags. Match local conventions (e.g., "cart" for EN-US, "basket" for EN-UK, "Warenkorb" for DE). Do not add politeness phrases the market does not use in UI.`,
    customInstructionsRequired: false,
    alwaysSuggestHumanReview: false,
  },
  {
    id: `informational`,
    displayName: `Informacyjna`,
    badge: `INFORMATIONAL`,
    group: `Informacyjne`,
    hint: `FAQ, O nas, płatności, dostawa`,
    useCases: [
      `FAQ`,
      `Strony "O nas"`,
      `Strony "Dostawa", "Płatności", "Zwroty"`,
      `Strona "Kontakt"`,
    ],
    goal: `Wzbudzić zaufanie — jasność, neutralność, brak sprzedażowego stylu.`,
    tone: `professional`,
    creativity: 2,
    strictness: 3,
    lengthGuidance: `Długość zbliżona do źródła, styl spójny w obrębie sekcji.`,
    optimizeFor: `Jasność i zaufanie, neutralny ton obsługi klienta`,
    protect: [
      `Liczby (czas dostawy, koszty, dni robocze)`,
      `Nazwy kurierów i metod płatności (PayU, BLIK, Klarna, PayPal)`,
      `Linki, e-maile, numery telefonów`,
      `Dane firmy i skróty (NIP, REGON)`,
    ],
    avoid: [
      `Przesadnej formalności, gdy rynek używa luźniejszego stylu`,
      `Dodawania obietnic, których nie ma w źródle`,
      `Kreatywnych metafor`,
    ],
    qualityChecks: [
      `Liczby i nazwy metod płatności 1:1`,
      `Linki, e-maile, telefony niezmienione`,
      `Styl spójny w obrębie sekcji`,
    ],
    systemInstruction: `You are translating informational pages (FAQ, About, Shipping, Payments). Aim for clarity and trust. Keep all numbers, payment method names, courier names, links, e-mails and phone numbers exactly as in the source. Match the target market's tone (e.g., EN-US slightly more conversational than DE). Do not add claims that are not in the source.`,
    customInstructionsRequired: false,
    alwaysSuggestHumanReview: false,
  },
  {
    id: `legal`,
    displayName: `Prawna`,
    badge: `LEGAL`,
    group: `Prawne`,
    hint: `Regulamin, polityka prywatności`,
    useCases: [
      `Regulaminy`,
      `Polityka prywatności`,
      `Polityka zwrotów`,
      `Informacje o bezpieczeństwie produktu, klauzule GDPR`,
    ],
    goal: `Nie zmieniać sensu prawnego — tłumaczenie bezpieczne, ostrożne, formalne, bez parafrazy.`,
    tone: `formal`,
    creativity: 1,
    strictness: 5,
    lengthGuidance: `Liczba zdań w sekcjach zbliżona do źródła; bez skracania długich zdań prawniczych.`,
    optimizeFor: `Wierność znaczeniu prawnemu`,
    protect: [
      `Terminy prawne w wersji właściwej dla prawa rynku docelowego`,
      `Numerację paragrafów i punktów`,
      `Referencje do aktów prawnych`,
      `Daty, kwoty, terminy`,
    ],
    avoid: [
      `Parafrazy zmieniającej znaczenie prawne`,
      `Dopowiadania reguł, których nie ma w źródle`,
      `Synonimów tam, gdzie termin prawny jest standardem`,
      `Skracania długich zdań prawniczych`,
    ],
    qualityChecks: [
      `Struktura paragrafów zachowana 1:1`,
      `Liczba zdań w sekcjach zbliżona do źródła`,
      `Terminy prawne spójne w całym tekście`,
      `Flaga zalecanego przeglądu człowieka zawsze ustawiona`,
    ],
    systemInstruction: `You are translating a legal document for an e-commerce store. Your highest priority is preserving the exact legal meaning. Use formal language. Keep paragraph and clause numbering intact. Do not paraphrase. Where a Polish legal term has an established equivalent in the target legal system, use it; otherwise translate literally and add a translator's note in qualityNotes. Always recommend human legal review for the output.`,
    customInstructionsRequired: false,
    alwaysSuggestHumanReview: true,
  },
  {
    id: `universal`,
    displayName: `Uniwersalna`,
    badge: `UNIVERSAL`,
    group: `Uniwersalne`,
    hint: `Tłumaczenie ogólne, brak profilu`,
    useCases: [
      `Treści niepasujące do żadnego profilu`,
      `Sytuacje, gdy użytkownik nie zna typu treści`,
    ],
    goal: `Solidne, naturalne tłumaczenie na język docelowy — bez specjalizacji i agresywnej lokalizacji.`,
    tone: `neutral`,
    creativity: 3,
    strictness: 3,
    lengthGuidance: `Długość i liczba akapitów zbliżone do źródła.`,
    optimizeFor: `Solidne, naturalne tłumaczenie ogólne`,
    protect: [
      `Liczby, daty, jednostki, nazwy własne`,
      `Ogólną strukturę akapitów`,
    ],
    avoid: [
      `Radykalnej transkreacji`,
      `Dosłowności tam, gdzie język docelowy ma inną składnię`,
      `Zmiany rejestru (formalny / luźny)`,
    ],
    qualityChecks: [
      `Liczba akapitów zgodna ze źródłem`,
      `Liczby 1:1`,
      `Styl zbliżony do źródła`,
    ],
    systemInstruction: `You are doing a general, high-quality translation from Polish to the target language. Match the source's tone, structure and register. Preserve all numbers, dates, units and proper names. Use natural target-language phrasing rather than literal calques. This is the fallback profile — no specialization is applied.`,
    customInstructionsRequired: false,
    alwaysSuggestHumanReview: false,
  },
  {
    id: `custom_prompt`,
    displayName: `Własna instrukcja`,
    badge: `CUSTOM_PROMPT`,
    group: `Uniwersalne`,
    hint: `Pełna kontrola nad pipeline'em`,
    useCases: [
      `Użytkownik wpisuje własną instrukcję systemową`,
      `Kanał ucieczki, gdy żaden profil nie pasuje`,
    ],
    goal: `Maksymalna kontrola po stronie użytkownika przy zachowaniu zasad bezpieczeństwa (safety floor).`,
    tone: `user-defined`,
    creativity: 3,
    strictness: 3,
    lengthGuidance: `Zdeterminowana przez instrukcję użytkownika.`,
    optimizeFor: `Realizacja instrukcji użytkownika`,
    protect: [
      `Zawsze: liczby, jednostki, marki, modele (safety floor)`,
      `Placeholdery i markup`,
    ],
    avoid: [
      `Złamania zasad bezpieczeństwa (safety floor)`,
      `Generowania danych osobowych, których nie ma w źródle`,
      `Tonu obraźliwego lub dyskryminującego, niezależnie od instrukcji`,
    ],
    qualityChecks: [
      `Instrukcja użytkownika faktycznie zastosowana (opis w styleRationale)`,
      `Reguły safety floor nienaruszone`,
      `Placeholdery 1:1`,
    ],
    systemInstruction: `You are translating from Polish to the target language. The user has provided custom instructions, which you must follow as closely as possible. However, the following rules always apply regardless of the user's instructions: preserve all numbers, units, brand names, model names, SKUs, placeholders ({variable}, %s) and HTML/Markdown markup. Do not generate content that is offensive, discriminatory, or that fabricates personal data. After translating, briefly explain in styleRationale how you applied the user's instructions.`,
    customInstructionsRequired: true,
    alwaysSuggestHumanReview: false,
  },
];

/** Kolejność grup w dropdownie „Typ treści". */
export const PROFILE_GROUP_ORDER: ProfileGroup[] = [
  `Produktowe`,
  `SEO`,
  `Treści`,
  `Marketing`,
  `UI / System`,
  `Informacyjne`,
  `Prawne`,
  `Uniwersalne`,
];

/** Domyślny profil przy starcie aplikacji. */
export const DEFAULT_PROFILE: ProfileId = `product_long`;

const PROFILE_BY_ID: Record<ProfileId, TranslationProfile> = Object.fromEntries(
  PROFILES.map((profile) => [profile.id, profile]),
) as Record<ProfileId, TranslationProfile>;

/** Zwraca profil dla danego identyfikatora. */
export function getProfile(id: ProfileId): TranslationProfile {
  return PROFILE_BY_ID[id];
}

/** Zwraca profile pogrupowane do wyświetlenia w dropdownie. */
export function getGroupedProfiles(): { group: ProfileGroup; profiles: TranslationProfile[] }[] {
  return PROFILE_GROUP_ORDER.map((group) => ({
    group,
    profiles: PROFILES.filter((profile) => profile.group === group),
  }));
}
